[custom]

;规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Game_Download_CDN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/jijg1022/rule/refs/heads/main/DirectLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/jijg1022/rule/refs/heads/main/ProxyLite.list
ruleset=🤖 AI,https://raw.githubusercontent.com/jijg1022/rule/refs/heads/main/AI.list
ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
ruleset=🎮 游戏平台,[]GEOSITE,category-games
ruleset=🚀 节点选择,[]GEOSITE,gfw
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

;策略组定义
custom_proxy_group=🚀 节点选择`select`[]♻️ 港台日自动`[]✡️ 香港故转`[]✡️ 台湾故转`[]✡️ 日本故转`[]✡️ 韩国故转`[]✡️ 狮城故转`[]✡️ 美国故转`[]✡️ 其它故转`[]HK 香港节点`[]TW 台湾节点`[]JP 日本节点`[]KR 韩国节点`[]SG 狮城节点`[]US 美国节点`[]🌐 其它地区`[]🛩️ 手动选择`[]DIRECT
custom_proxy_group=🛩️ 手动选择`select`(?=.*(Hong Kong|Taiwan|Japan|Korea|Singapore|USA))^((?!(Premium)).)*$
custom_proxy_group=♻️ 港台日自动`url-test`(?=.*(Hong Kong|Taiwan|Japan))^((?!(Premium)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]✡️ 台湾故转`[]✡️ 日本故转`[]✡️ 韩国故转`[]✡️ 狮城故转`[]✡️ 美国故转`[]🛩️ 手动选择
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]✡️ 香港故转`[]✡️ 台湾故转`[]✡️ 日本故转`[]✡️ 韩国故转`[]✡️ 美国故转`[]🛩️ 手动选择`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🛩️ 手动选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🛩️ 手动选择
custom_proxy_group=✡️ 香港故转`url-test`(?=.*(Hong Kong))^((?!(Premium)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✡️ 台湾故转`url-test`(?=.*(Taiwan))^((?!(Premium)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✡️ 日本故转`url-test`(?=.*(Japan))^((?!(Premium)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✡️ 韩国故转`url-test`(?=.*(Korea))^((?!(Premium)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✡️ 狮城故转`url-test`(?=.*(Singapore))^((?!(Premium)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✡️ 美国故转`url-test`(?=.*(USA))^((?!(Premium)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✡️ 其它故转`url-test`^((?!((?i)Hong Kong|Taiwan|Japan|Korea|Singapore|USA|Premium|Expire|Traffic|500)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=HK 香港节点`select`(?=.*(Hong Kong))^((?!(Premium)).)*$
custom_proxy_group=TW 台湾节点`select`(?=.*(Taiwan))^((?!(Premium)).)*$
custom_proxy_group=JP 日本节点`select`(?=.*(Japan))^((?!(Premium)).)*$
custom_proxy_group=KR 韩国节点`select`(?=.*(Korea))^((?!(Premium)).)*$
custom_proxy_group=SG 狮城节点`select`(?=.*(Singapore))^((?!(Premium)).)*$
custom_proxy_group=US 美国节点`select`(?=.*(USA))^((?!(Premium)).)*$
custom_proxy_group=🌐 其它地区`select`^((?!((?i)Hong Kong|Taiwan|Japan|Korea|Singapore|USA|Premium|Expire|Traffic|500)).)*$

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
